@startuml

skinparam componentStyle uml2

component [LearnerContext]
note right of [LearnerContext]
Quản lý định danh học viên (Learner), 
hồ sơ và tiến trình cá nhân. 
end note
component [LearningContext]
note right of [LearningContext]
Core domain cung cấp kho bài tập, 
đề thi TOEIC và chấm điểm. 
end note
component [SubscriptionContext]
note right of [SubscriptionContext]
Xử lý thanh toán qua VNPay, MoMo, 
ZaloPay và quản lý các gói cước 
theo thời gian. 
end note

interface "Upstream-Downstream" as LearnerContext_to_SubscriptionContext
[SubscriptionContext] --> LearnerContext_to_SubscriptionContext : OPEN_HOST_SERVICE, PUBLISHED_LANGUAGE
LearnerContext_to_SubscriptionContext <.. [LearnerContext] : use via ANTICORRUPTION_LAYER

interface "Upstream-Downstream" as LearningContext_to_LearnerContext
[LearnerContext] --> LearningContext_to_LearnerContext : OPEN_HOST_SERVICE
LearningContext_to_LearnerContext <.. [LearningContext] : consume



@enduml
