@startuml

skinparam componentStyle uml2

component [UserManagementService]
note right of [UserManagementService]
Quản lý thông tin, xác thực và 
phân quyền người dùng. 
end note
component [ProductCatalogService]
note right of [ProductCatalogService]
Quản lý danh mục, mô tả và giá 
cả của các sản phẩm. 
end note
component [OrderProcessingService]
note right of [OrderProcessingService]
Xử lý vòng đời của các đơn đặt 
hàng. 
end note
component [InventoryService]
note right of [InventoryService]
Theo dõi số lượng hàng tồn kho 
và các kho bãi. 
end note
component [PaymentGatewayService]
note right of [PaymentGatewayService]
Xử lý các giao dịch thanh toán 
với đối tác bên thứ ba. 
end note
component [NotificationService]
note right of [NotificationService]
Gửi email, SMS và thông báo đẩy 
(push notifications). 
end note
component [ReviewAndRatingService]
note right of [ReviewAndRatingService]
Lưu trữ và hiển thị các đánh giá, 
bình luận của khách hàng. 
end note
component [ShippingService]
note right of [ShippingService]
Tính toán phí vận chuyển và theo 
dõi lộ trình giao hàng. 
end note
component [CustomerSupportService]
note right of [CustomerSupportService]
Hỗ trợ khách hàng qua hệ thống 
ticket và live chat. 
end note
component [RecommendationService]
note right of [RecommendationService]
Đề xuất sản phẩm dựa trên hành 
vi và lịch sử duyệt web. 
end note



@enduml
